import type { Metadata } from "next";
import "@/scss/main.scss";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { unstable_setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = locale ? await getMessages({ locale }) : {};

  unstable_setRequestLocale(locale);
  return (
    <NextIntlClientProvider locale={locale || "en"} messages={messages}>
      <html lang={locale || "en"}>
        <body>{children}</body>
      </html>
    </NextIntlClientProvider>
  );
}
